### ISSUE TITLE
incorrect string serialization

### ISSUE THREAD

**Issue by deil** [aarongough/sexpistol#1]
Current version serializes strings without quotes. This code clearly shows the issue:
s = Sexpistol.new
s.parse_string(s.to_sexp(s.parse_string('"01qwerty"')))

Result will be [[1, :qwerty]], but expected ["01qwerty"]

**Comment by hsanjuan** [comment]
Same with IPs or Mac addresses...

**Comment by aarongough** [comment]
Hello Anton and Hector!
Obviously this issue is very old and you likely aren't using this gem any more, but I wanted to let you know that I have just done a large refactor/refresh of this project and as part of that the issues you mentioned have been fixed!

One confounding factor: `"01qwerty"` is not a valid s-expression, the correct equivalent is `("01qwerty")`. The new version will raise an error when trying to parse an invalid s-expression like `"01qwerty"`.

The project is vastly improved in all regards, and I hope it will be helpful if you still have a need for parsing s-expressions!

Let me know if you find any issues.

Best regards,
Aaron
